# Generated by Django 3.2.14 on 2022-07-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_profile_postal_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
