# Generated by Django 3.2.14 on 2022-07-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='sender',
        ),
    ]
