# Generated by Django 3.2.14 on 2022-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_courier_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
