# Generated by Django 3.2.14 on 2022-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_courier_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='courier',
            name='weight',
            field=models.CharField(max_length=4),
        ),
    ]
