# Generated by Django 3.2.14 on 2022-07-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20220721_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
